### ISSUE TITLE
Creating new environment fails on node src copy

### ISSUE THREAD

**Issue by LeZuse** [ekalinin/nodeenv#106]
```
> nodeenv --prebuilt env
 * Install node.js (0.10.33) ..usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
Traceback (most recent call last):
  File "/usr/local/bin/nodeenv", line 9, in <module>
    load_entry_point('nodeenv==0.11.1', 'console_scripts', 'nodeenv')()
  File "/Library/Python/2.7/site-packages/nodeenv-0.11.1-py2.7.egg/nodeenv.py", line 765, in main
    create_environment(env_dir, opt)
  File "/Library/Python/2.7/site-packages/nodeenv-0.11.1-py2.7.egg/nodeenv.py", line 674, in create_environment
    install_node(env_dir, src_dir, opt)
  File "/Library/Python/2.7/site-packages/nodeenv-0.11.1-py2.7.egg/nodeenv.py", line 561, in install_node
    copy_node_from_prebuilt(env_dir, src_dir)
  File "/Library/Python/2.7/site-packages/nodeenv-0.11.1-py2.7.egg/nodeenv.py", line 483, in copy_node_from_prebuilt
    callit(['cp', '-a', src_dir + '/node-v*/*', env_dir], True, env_dir)
  File "/Library/Python/2.7/site-packages/nodeenv-0.11.1-py2.7.egg/nodeenv.py", line 420, in callit
    % (cmd_desc, proc.returncode))
OSError: Command cp -a /Users/jenkins/Jenki...ce/env/src/node-v*/* /Users/jenkins/Jenki...Plugin/workspace/env failed with error code 64
```

Why is this https://github.com/ekalinin/nodeenv/blob/master/nodeenv.py#L372 needed?
The full path is `/Users/jenkins/JenkinsHome/jobs/iOS Hat Plugin/workspace/env/src/node-v*/*`. Looks like a problem with spaces in the path.

**Comment by harshilsharma63** [comment]
I spent about a day trying to figure why the hell was my build job failing, and this seems to be the reason. Really? Not handling spaces?

**Comment by ekalinin** [comment]
Looks like fixed :)

```sh
➜ mkdir dir\ w\ spaces
➜ cd dir\ w\ spaces 
➜ virtualenv -p python3.8 .env        
➜ source .env/bin/activate 
➜ pip install nodeenv            
Collecting nodeenv
  Downloading nodeenv-1.6.0-py2.py3-none-any.whl (21 kB)
Installing collected packages: nodeenv
Successfully installed nodeenv-1.6.0
➜ nodeenv -p                                           
 * Install prebuilt node (16.1.0) ..... done.
 * Appending data to ~/tmp/dir w spaces/.env/bin/activate
 * Appending data to ~/tmp/dir w spaces/.env/bin/activate.fish
➜ node -v                 
v16.1.0
➜ where node
~/tmp/dir w spaces/.env/bin/node
```
