### ISSUE TITLE
Failing to install prebuilt node, tar is coming back as html

### ISSUE THREAD

**Issue by asottile** [ekalinin/nodeenv#130]
```
$ nodeenv nenv --prebuilt
 * Install node (4.0.0Traceback (most recent call last):
  File .../virtualenv_run/bin/nodeenv", line 11, in <module>
    sys.exit(main())
  File ".../virtualenv_run/lib/python2.7/site-packages/nodeenv.py", line 890, in main
    create_environment(env_dir, opt)
  File ".../virtualenv_run/lib/python2.7/site-packages/nodeenv.py", line 731, in create_environment
    install_node(env_dir, src_dir, opt)
  File ".../virtualenv_run/lib/python2.7/site-packages/nodeenv.py", line 600, in install_node
    download_node(node_url, src_dir, env_dir, opt)
  File ".../virtualenv_run/lib/python2.7/site-packages/nodeenv.py", line 491, in download_node
    with tarfile_open(fileobj=tar_contents) as tarfile_obj:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File ".../virtualenv_run/lib/python2.7/site-packages/nodeenv.py", line 479, in tarfile_open
    tf = tarfile.open(*args, **kwargs)
  File "/usr/lib64/python2.7/tarfile.py", line 1665, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

From poking a bit this is what is coming back from this url:

```
(Pdb) kwargs['fileobj'].read()
'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="utf-8">\n    <title>Node.js</title>\n\n   ... a bunch more crap ... '
...
(Pdb) node_url
u'http://nodejs.org/dist/v4.0.0/node-v4.0.0-linux-x64.tar.gz'
```

Seems they've switched to https?

**Comment by asottile** [comment]
yeah, confirmed changing it to https fixes this, I'll write up a patch

**Comment by ekalinin** [comment]
Should be fixed as well.
