### ISSUE TITLE
nodeenv npm install fails

### ISSUE THREAD

**Issue by djMax** [ekalinin/nodeenv#143]
```nodeenv --node=4.2.2 --with-npm --npm=3.4.1 --prebuilt sdkenv```

yields

```
Setting up nodeenv
 * Install node (4.2.2)... done.
 * Install npm.js (3.4.1) ... done.
module.js:339
    throw err;
    ^

Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/data/jenkins/jobs/retail-sdk-js/workspace/sdkenv/lib/node_modules/npm/lib/cache/caching-client.js:9:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by ekalinin** [comment]
Hi @djMax 

Thanks for report.
I tested the same command as you, here's my result:

```bash
➥ cat /etc/issue
Ubuntu 15.10 \n \l
➥ virtualenv env
➥ . env/bin/activate
(env) ➥ pip install nodeenv
(env) ➥ nodeenv --node=4.2.2 --with-npm --npm=3.4.1 --prebuilt sdkenv
 * Install node (4.2.2)... done.
 * Install npm.js (3.4.1) ... done.
```

but it seems like there's some error in the `npm` itself, not in the `nodeenv`:

```bash
(env) ➥ deactivate 
➥ . sdkenv/bin/activate
(sdkenv) ➥ node -v
v4.2.2
(sdkenv) ➥ npm -v
module.js:339
    throw err;
    ^

Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/tmp/sdkenv/lib/node_modules/npm/lib/cache/caching-client.js:9:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```
