### ISSUE TITLE
nodeenv -p produces OSError: Command make --jobs=2 failed with error code 2

### ISSUE THREAD

**Issue by fulv** [ekalinin/nodeenv#171]
I am running into the following error when `nodeenv -p`.  

```
(precise)fulvio@localhost:~$ uname -a
Linux localhost 3.14.0 #1 SMP PREEMPT Tue Aug 2 21:07:06 PDT 2016 armv7l armv7l armv7l GNU/Linux

(precise)fulvio@localhost:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise

(precise)fulvio@localhost:~$ which virtualenv
/usr/local/bin/virtualenv

(precise)fulvio@localhost:~$ virtualenv testenv
New python executable in /home/fulvio/testenv/bin/python
Installing setuptools, pip, wheel...done.

(precise)fulvio@localhost:~$ source testenv/bin/activate

(testenv) (precise)fulvio@localhost:~$ pip install nodeenv
Collecting nodeenv
Installing collected packages: nodeenv
Successfully installed nodeenv-0.13.6

(testenv) (precise)fulvio@localhost:~$ nodeenv -p
 * Install node (6.5.0)..Traceback (most recent call last):
  File "/home/fulvio/testenv/bin/nodeenv", line 11, in <module>
    sys.exit(main())
  File "/home/fulvio/testenv/local/lib/python2.7/site-packages/nodeenv.py", line 891, in main
    create_environment(env_dir, opt)
  File "/home/fulvio/testenv/local/lib/python2.7/site-packages/nodeenv.py", line 732, in create_environment
    install_node(env_dir, src_dir, opt)
  File "/home/fulvio/testenv/local/lib/python2.7/site-packages/nodeenv.py", line 608, in install_node
    build_node_from_src(env_dir, src_dir, node_src_dir, opt)
  File "/home/fulvio/testenv/local/lib/python2.7/site-packages/nodeenv.py", line 577, in build_node_from_src
    callit([make_cmd] + make_opts, opt.verbose, True, node_src_dir, env)
  File "/home/fulvio/testenv/local/lib/python2.7/site-packages/nodeenv.py", line 461, in callit
    % (cmd_desc, proc.returncode))
OSError: Command make --jobs=2 failed with error code 2
```

If I try with --prebuilt, I get:

```
testenv) (precise)fulvio@localhost:~$ nodeenv -p --prebuilt
 * Install node (6.5.0Traceback (most recent call last):
  File "/home/fulvio/testenv/bin/nodeenv", line 11, in <module>
    sys.exit(main())
  File "/home/fulvio/testenv/local/lib/python2.7/site-packages/nodeenv.py", line 891, in main
    create_environment(env_dir, opt)
  File "/home/fulvio/testenv/local/lib/python2.7/site-packages/nodeenv.py", line 732, in create_environment
    install_node(env_dir, src_dir, opt)
  File "/home/fulvio/testenv/local/lib/python2.7/site-packages/nodeenv.py", line 595, in install_node
    node_url = get_node_src_url(opt.node, get_node_src_url_postfix(opt))
  File "/home/fulvio/testenv/local/lib/python2.7/site-packages/nodeenv.py", line 503, in get_node_src_url_postfix
    postfix_arch = arches[platform.machine()]
KeyError: 'armv7l'
```

**Comment by ekalinin** [comment]
Hey @fulv 

Thanks for report. 
I've added some support for the `arm` arch.
Please, try `nodeenv` from `master` branch.

**Comment by fulv** [comment]
Works, thanks!
