### ISSUE TITLE
error 17 file exists on brand new env

### ISSUE THREAD

**Issue by kudlatyamroth** [ekalinin/nodeenv#188]
after creating env:
 ```
virtualenv test
source test/bin/activate
nodeenv -p --prebuilt
 * Install prebuilt node (8.1.3) ....Traceback (most recent call last):
  File "/home/Downloads/nodeenv/bin/nodeenv", line 11, in <module>
    sys.exit(main())
  File "/home/Downloads/nodeenv/lib/python3.6/site-packages/nodeenv.py", line 1022, in main
    create_environment(env_dir, opt)
  File "/home/Downloads/nodeenv/lib/python3.6/site-packages/nodeenv.py", line 855, in create_environment
    install_node(env_dir, src_dir, opt)
  File "/home/Downloads/nodeenv/lib/python3.6/site-packages/nodeenv.py", line 675, in install_node
    copy_node_from_prebuilt(env_dir, src_dir, opt.node)
  File "/home/Downloads/nodeenv/lib/python3.6/site-packages/nodeenv.py", line 587, in copy_node_from_prebuilt
    copytree(src_folder, env_dir)
  File "/home/Downloads/nodeenv/lib/python3.6/site-packages/nodeenv.py", line 568, in copytree
    shutil.copytree(s, d, symlinks, ignore)
  File "/home/Downloads/nodeenv/lib/python3.6/shutil.py", line 315, in copytree
    os.makedirs(dst)
  File "/home/Downloads/nodeenv/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/Downloads/nodeenv/share'
```

this is only on 1.1.3, with 1.1.2 is everything ok.

**Comment by ekalinin** [comment]
Hey, 

Thanks for report. Will fix asap.
Caused by #187
