### ISSUE TITLE
nodeenb 1.1.3 and 1.1.4 Symlink to env/bbin/npm fails if npm already exists. 1.1.2 works fine.

### ISSUE THREAD

**Issue by lsmithso** [ekalinin/nodeenv#189]
nodeenb 1.1.3 and 1.1.4 Symlink to env/bbin/npm fails if npm already
exists. 1.1.2 works fine.

Reproduce by running nodeenv 2 or more times in the same venv.

nodeenv --python-virtualenv --prebuilt --node=7.10.0
nodeenv --python-virtualenv --prebuilt --node=7.10.0

nodeenv --python-virtualenv --prebuilt --node=7.10.0
 * Install prebuilt node (7.10.0) ....Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/gryphon/workspace/env/bin/nodeenv", line 11, in <module>
    sys.exit(main())
  File "/var/lib/jenkins/jobs/gryphon/workspace/env/local/lib/python2.7/site-packages/nodeenv.py", line 1028, in main
    create_environment(env_dir, opt)
  File "/var/lib/jenkins/jobs/gryphon/workspace/env/local/lib/python2.7/site-packages/nodeenv.py", line 861, in create_environment
    install_node(env_dir, src_dir, opt)
  File "/var/lib/jenkins/jobs/gryphon/workspace/env/local/lib/python2.7/site-packages/nodeenv.py", line 681, in install_node
    copy_node_from_prebuilt(env_dir, src_dir, opt.node)
  File "/var/lib/jenkins/jobs/gryphon/workspace/env/local/lib/python2.7/site-packages/nodeenv.py", line 593, in copy_node_from_prebuilt
    copytree(src_folder, env_dir, True)
  File "/var/lib/jenkins/jobs/gryphon/workspace/env/local/lib/python2.7/site-packages/nodeenv.py", line 571, in copytree
    copytree(s, d, symlinks, ignore)
  File "/var/lib/jenkins/jobs/gryphon/workspace/env/local/lib/python2.7/site-packages/nodeenv.py", line 574, in copytree
    os.symlink(os.readlink(s), d)
OSError: [Errno 17] File exists

nodeenb 1.1.3 and 1.1.4 Symlink to env/bbin/npm fails if npm already exists. 1.1.2 works fine.

Reproduce by running nodeenv 2 or more times in the same venv.

nodeenv --python-virtualenv --prebuilt --node=7.10.0
nodeenv --python-virtualenv --prebuilt --node=7.10.0

nodeenv --python-virtualenv --prebuilt --node=7.10.0
 * Install prebuilt node (7.10.0) ....Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/gryphon/workspace/env/bin/nodeenv", line 11, in <module>
    sys.exit(main())
  File "/var/lib/jenkins/jobs/gryphon/workspace/env/local/lib/python2.7/site-packages/nodeenv.py", line 1028, in main
    create_environment(env_dir, opt)
  File "/var/lib/jenkins/jobs/gryphon/workspace/env/local/lib/python2.7/site-packages/nodeenv.py", line 861, in create_environment
    install_node(env_dir, src_dir, opt)
  File "/var/lib/jenkins/jobs/gryphon/workspace/env/local/lib/python2.7/site-packages/nodeenv.py", line 681, in install_node
    copy_node_from_prebuilt(env_dir, src_dir, opt.node)
  File "/var/lib/jenkins/jobs/gryphon/workspace/env/local/lib/python2.7/site-packages/nodeenv.py", line 593, in copy_node_from_prebuilt
    copytree(src_folder, env_dir, True)
  File "/var/lib/jenkins/jobs/gryphon/workspace/env/local/lib/python2.7/site-packages/nodeenv.py", line 571, in copytree
    copytree(s, d, symlinks, ignore)
  File "/var/lib/jenkins/jobs/gryphon/workspace/env/local/lib/python2.7/site-packages/nodeenv.py", line 574, in copytree
    os.symlink(os.readlink(s), d)
OSError: [Errno 17] File exists

**Comment by yingzuo** [comment]
I got the same error with v1.2.0.

**Comment by lsmithso** [comment]
Hi:

My son had agreed to accompany me to Stratford next Wednesday. 12-1300
would suit us well. I'll be bringing my guide dog along. Will the dog
be needed for the research? If not my son would like to take the
opportunity to walk him around the park while we're busy.



Ying Zuo writes:
 > I got the same error with v1.2.0.
 > 
 > -- 
 > You are receiving this because you authored the thread.
 > Reply to this email directly or view it on GitHub:
 > https://github.com/ekalinin/nodeenv/issues/189#issuecomment-320838162

-- 
Les Smithson

**Comment by lsmithso** [comment]
I tried this again with 1.2 .0 and its still a problem. Any chance of
a fix?

**Comment by jaraco** [comment]
Here's where the error [occurs in the current master](https://github.com/ekalinin/nodeenv/blob/42765a0c3e3cda420209293772b36f14ea03e07e/nodeenv.py#L581).
