### ISSUE TITLE
Riscv64 architecture support - incorrect keymap

### ISSUE THREAD

**Issue by FantasqueX** [ekalinin/nodeenv#304]
I'm making packages for riscv64 ArchLinux and find some error due to riscv64 architecture key hasn't been added yet.
Would you consider to add riscv64 architecture?
```
Traceback (most recent call last):
  File "/usr/sbin/nodeenv", line 33, in <module>
    sys.exit(load_entry_point('nodeenv==1.6.0', 'console_scripts', 'nodeenv')())
  File "/usr/lib/python3.10/site-packages/nodeenv.py", line 1079, in main
    create_environment(env_dir, opt)
  File "/usr/lib/python3.10/site-packages/nodeenv.py", line 956, in create_environment
    install_node(env_dir, src_dir, opt)
  File "/usr/lib/python3.10/site-packages/nodeenv.py", line 721, in install_node
    install_node_wrapped(env_dir, src_dir, opt)
  File "/usr/lib/python3.10/site-packages/nodeenv.py", line 737, in install_node_wrapped
    node_url = get_node_bin_url(opt.node)
  File "/usr/lib/python3.10/site-packages/nodeenv.py", line 537, in get_node_bin_url
    'arch': archmap[platform.machine()],
KeyError: 'riscv64'
```

**Comment by FantasqueX** [comment]
I noticed that there is no nodejs build for riscv64, so a fix is impossible.
