### ISSUE TITLE
Version discovery regression

### ISSUE THREAD

**Issue by Alexander-Shukaev** [ekalinin/nodeenv#356]
#352 broke version discovery (made it less robust basically):

```text
which: no nodejs in (/tests/.venv/bin:/opt/bb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bb/lib64/bin)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/tests/.venv/lib/python3.11/site-packages/nodeenv.py", line 1544, in <module>
    main()
  File "/tests/.venv/lib/python3.11/site-packages/nodeenv.py", line 1126, in main
    create_environment(env_dir, args)
  File "/tests/.venv/lib/python3.11/site-packages/nodeenv.py", line 1011, in create_environment
    if node_version_from_args(args) < (0, 6, 3) or args.with_npm:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tests/.venv/lib/python3.11/site-packages/nodeenv.py", line 188, in node_version_from_args
    return parse_version(clear_output(out))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tests/.venv/lib/python3.11/site-packages/nodeenv.py", line 178, in parse_version
    return tuple(map(int, version_str.replace('v', '').split('.')))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '2+2-b20240418T00453999'
```

**Comment by Alexander-Shukaev** [comment]
```
'/.venv/bin/python3.11', '-mnodeenv', '--prebuilt', '--clean-src', '/.pre-commit/repo2vdt1csj/node_env-system', '-n', 'system'
```

**Comment by ekalinin** [comment]
Hey, 

Please, try new version - 1.9.1.
