### ISSUE TITLE
`nodeenv -n system` exits `0` when curl is not found

### ISSUE THREAD

**Issue by asottile** [ekalinin/nodeenv#61]
```
$ nodeenv -n system nenv2
/bin/sh: 1: curl: not found
 * Install npm.js (latest) ... done.
(venv)asottile@asottile-VirtualBox:/tmp/foo$ echo $?
0
```

Interestingly it returns a nonzero code without -n system:

```
$ nodeenv nenv3
/bin/sh: 1: curl: not found
 * Install node.js (-RC1) Traceback (most recent call last):
  File "/tmp/foo/venv/bin/nodeenv", line 9, in <module>
    load_entry_point('nodeenv==0.8.0', 'console_scripts', 'nodeenv')()
  File "/tmp/foo/venv/local/lib/python2.7/site-packages/nodeenv.py", line 596, in main
    create_environment(env_dir, opt)
  File "/tmp/foo/venv/local/lib/python2.7/site-packages/nodeenv.py", line 516, in create_environment
    install_node(env_dir, src_dir, opt)
  File "/tmp/foo/venv/local/lib/python2.7/site-packages/nodeenv.py", line 378, in install_node
    download_node(node_url, src_dir, env_dir, opt)
  File "/tmp/foo/venv/local/lib/python2.7/site-packages/nodeenv.py", line 347, in download_node
    callit(cmd, opt.verbose, True, env_dir)
  File "/tmp/foo/venv/local/lib/python2.7/site-packages/nodeenv.py", line 309, in callit
    % (cmd_desc, proc.returncode))
OSError: Command curl --silent -L http://nodejs.org/dist/node-v-RC1.tar.gz | tar xzf - -C /tmp/foo/nenv3/src failed with error code 2
(venv)asottile@asottile-VirtualBox:/tmp/foo$ echo $?
1
```

Yes I realize I'm probably the only person who has a linux installation that has yet to install curl.  To be fair this is a relatively new install :D

**Comment by asottile** [comment]
I believe #110 solves this?
